### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by beepy0** [beepy0/thesis#35]
### VTune
 - [x] Note down a plan on how to run initial VTune Hotspot Analysis
- implement dynamic values for static variables, test if that works
- comment out all prints
- put a sleep 10 between the two update loops

### SIMD
- [x] Rewrite function definitions to use as few different variable types as possible.
- [x] Import libsimdpp to the project (https://foonathan.net/blog/2016/07/07/cmake-dependency-handling.html); import libraries via cmakelists.txt https://stackoverflow.com/questions/44998233/add-external-c-libraries-to-a-clion-project
- [x] Run the sample code to make sure the library works.
- [x] Diagnose p_reses' first 10-100 results and analyze resulting values
- [x] Research server CPU model and highest AVX512 version support

### Benchmarks
- [x] Make dummy data
- [x] Implement sample diagram with dummy data
- [x] Make sure that each run uses random values for variables that need random values
- [x] Implement saving metrics in a file for each test run
- [x] Decide on test cases data (^^^Rx^^^B sizes)
- [x] Compile different test cases
- [x] Book critical timeslot on server
- [x] Organize test folder on server, create a separate folder for this test
- [x] Run tests x-times each and collect data in the output file
- [x] Transfer data to diagram
