### ISSUE TITLE
Theory Research

### ISSUE THREAD

**Issue by beepy0** [beepy0/thesis#5]
### Milestone 1
- [x] K-independent hashing : https://en.wikipedia.org/wiki/K-independent_hashing
- [x] Get inspired by other papers that use SIMD optimizations.
- [x] Roofline Model : https://en.wikipedia.org/wiki/Roofline_model Looks like a good way to represent the algorithm bottlenecks.
- [x] Self-Join : https://www.w3resource.com/sql/joins/perform-a-self-join.php
- [x] Distributed Join Operations (**Distributed query processing**)
- [ ] C/C++ Pointer aliasing
