### ISSUE TITLE
Literature and Programming Research

### ISSUE THREAD

**Issue by beepy0** [beepy0/thesis#7]
The first milestone consists of mainly doing research on the theory and technology that I'm going to be using for this project. The plan currently consists of the following goals:
- [x] #10 #11 Research algorithms in detail
- [x] #3 Study visualization techniques for informative and simple paper diagrams
- [x] #4 Study programming language (C++)
- [x] Test the supplied remote PC (remote control via SSH, packages, etc.)
- [x] #6 Understand SIMD and AVX-512 instructions for C-like languages
- [x] #9 Understand technical aspects of CPU analysis with VTune Amplifier
- [x] #8 Test out VTune Amplifier’s CLI on local and remote machines
- [x] #30 Gather sources and information useful for the **Related Work** subsection
